[package]
name = "cargo-tarpaulin"
version = "0.5.6"
authors = ["Daniel McKenna <danielmckenna93@gmail.com>"]
description = "Cargo-Tarpaulin is a tool to determine code coverage achieved via tests"
repository = "https://github.com/xd009642/tarpaulin"
readme = "README.md"
license = "MIT/Apache-2.0"
categories = ["development-tools"]
keywords = ["cargo", "cargo-subcommand", "testing"]

[[bin]]
name = "cargo-tarpaulin"

[dependencies]
nix = "0.10.0"
libc = "0.2.39"
gimli = "0.15.0"
fallible-iterator = "0.1.3"
memmap = "0.6.2"
object = "0.7"
rustc-demangle = "0.1.7"
cargo = "0.24"
clap = "2.31.2"
serde = "1.0.34"
serde_json = "1.0.13"
coveralls-api = "0.3.3"
quick-xml = "0.12.1"
rustc-ap-syntax = "55.0.0"
regex = "0.2.10"
lazy_static = "1.0"
